#!/usr/bin/env bash
# Regenerate reference/protocol-versions.json from Minestom's release tags.
# Usage: rebuild-protocol-map.sh [path/to/minestom-clone]
set -eu

REPO="${1:-$HOME/references/minestom}"
OUT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/reference/protocol-versions.json"

[ -d "$REPO/.git" ] || { echo "not a git repo: $REPO" >&2; exit 1; }
git -C "$REPO" fetch --quiet --tags 2>/dev/null || true

for tag in $(git -C "$REPO" tag --sort=-creatordate); do
    body=$(git -C "$REPO" show "$tag:src/autogenerated/java/net/minestom/server/MinecraftConstants.java" 2>/dev/null \
        || git -C "$REPO" show "$tag:src/main/java/net/minestom/server/MinecraftServer.java" 2>/dev/null) || continue
    name=$(printf '%s' "$body" | grep -oP 'VERSION_NAME\s*=\s*"\K[^"]+' | head -1)
    proto=$(printf '%s' "$body" | grep -oP 'PROTOCOL_VERSION\s*=\s*\K[0-9]+' | head -1)
    [ -n "$proto" ] && [ -n "$name" ] && echo "$proto $name"
done | sort -u | python3 -c '
import json, sys
table = {}
for line in sys.stdin:
    protocol, name = line.split()
    table.setdefault(protocol, [])
    if name not in table[protocol]:
        table[protocol].append(name)
ordered = {k: (v[0] if len(v) == 1 else sorted(v))
           for k, v in sorted(table.items(), key=lambda kv: -int(kv[0]))}
print(json.dumps(ordered, indent=2))
' > "$OUT"

echo "wrote $OUT"
cat "$OUT"
